### ISSUE TITLE
Add a "zero" control for segment beginning

### ISSUE THREAD

**Issue by erkinalp** [ajayyy/SponsorBlock#1478] opened 2022-09-18 16:49 UTC
There are lots of segments that need to be placed right in the beginning of a video. A zero shortcut would be very useful. If the start box is filled and the end box is unfilled, the zero shortcut should move the existing input in the start into the end box.

**Comment by mchangrh** [comment] 2023-03-08 05:51
duplicate of #880

**Closed** 2023-03-08 14:18 UTC
