### ISSUE TITLE
Media buttons stop working after skipping a segment with audio notification on skip

### ISSUE THREAD

**Issue by Danstiv** [ajayyy/SponsorBlock#1053] opened 2021-11-23 11:56 UTC
### Hardware and software
Some bluetooth headphones called bt12.
Logitech keyboard k 270.
I think any device with multimedia buttons will do.
Windows 10 21H1 (64-bit) build 19043.1052
Google Chrome 96.0.4664.45
SponsorBlock (installed from chrome webstore) 3.6.1.
### Steps to reproduce
1. Connect your device with multimedia buttons to your computer.
2. Open the video for which the segments were sent (for example [this](https://www.youtube.com/watch?v=2USiC66uIMQ)).
3. Make sure the media buttons are working (just check play / pause).
4. Continue watching to segment.
5. After skipping (auto skip must be enabled) check the multimedia buttons again.
### Actual behavior
Media buttons no longer work
### Expected behavior
Multimedia buttons continue to work after skipping a segment.
### Notes
As mentioned above, I used bluetooth headphones as a device with multimedia keys.
Also, my logitech k270 keyboard has a play / pause button that works before skipping and stops working after skipping a segment.

**Comment by mchangrh** [comment] 2021-11-25 20:05
Could not reproduce 


multimedia keys work on wired keyboard/ media remapped keys (Corsair K70/ Logi G502) and through bluetooth (Aukey BR-C1) albeit delayed

W10 21H1 19043.1387"
Chrome 96.0.4664.45
SB 3.6.2

**Comment by Danstiv** [comment] 2021-11-26 06:47
I found a setting that affects this.
I have the audioNotificationOnSkip setting enabled.
It really works, when a segment is skipped, a sound signal is played.
And, apparently, at the same time something happens with the audio focus, because of which the multimedia buttons stop working.
Try to reproduce with the sound notification turned on.

**Comment by mchangrh** [comment] 2021-11-26 08:53
I can recreate it consistently with audioNotificationOnSkip

**Comment by madushans** [comment] 2022-01-20 22:36
I can reproduce this (or something very similar) on Edge.

Edge 97.0.1072.62
Windows 11 21H2 22000 434
Pay/Pause button mapped to a custom mouse button
SponsorBlock configured to skip sponsor and non-music blocks

When a segment is auto skipped at the beginning, Edge does not respond to the pay/pause button.

When SponsorBlock is configured to only show the block in seekbar and not auto skip.
Skipping blocks manually does not cause this issue it seems.

Disabling the audio notification on skip as @Danstiv mentioned fixes the issue.

**Comment by mchangrh** [comment] 2022-02-06 20:11
fixed in #1155

**Closed** 2022-02-06 21:14 UTC
