### ISSUE TITLE
Automatically jumps on new video in playlist

### ISSUE THREAD

**Issue by Synetech** [ajayyy/SponsorBlock#1268] opened 2022-04-05 13:23 UTC
When SponsorBlock is active while watching a playlist, when a video ends and the next video has segments, SponsorBlock will automatically jump past the first segment, thus skipping all of the non-blocked parts of the new video.

For example, if I'm watching a playlist and video 2 has a 10-second segment marked at 3:00 in, SponsorBlock will automatically jump to 3:10 as soon as video B starts. Worse, if video 3 has a single segment marked at the end of the video, SponsorBlock will skip right to the end of it when it starts, thus skipping the whole video.

**Comment by mchangrh** [comment] 2022-04-16 21:32
can you send a playlist example? I know you tend to watch it in embeds or weird combinations and I can't repro on  
`https://www.youtube.com/watch?v=videoID&list=PLID`

**Comment by Synetech** [comment] 2022-04-17 13:45
"Weird combinations." lol It's just Firefox with TamperMonkey userscripts and user stylesheets I wrote to make YouTube actually usable(-ish). 😀

I found a playlist with some videos that do the skipping problem. (I can't test it with an empty Firefox profile myself because SponsorBlock doesn't seem to work at all, it says "no YouTube video found", it only works with my worn-in profile with addons and such. 🤔)

https://www.youtube.com/playlist?list=PLee4zQaVZHIrKQiosLUxSncn0SayND8SF

At the end of the first video, the second video jumps straight to the segment in the middle, then at the end of the second video, it skips the last bit and jumps to the middle of the third video. If I click the middle of the scrubber to seek back to an earlier part of the third video, it jumps to the segment again. It takes another click to actually move back. Likewise, pressing 0 to seek to the beginning doesn't work when a video first starts, SB just jumps to the first segment again and I (usually) have to press 0 at least twice to get it to play from the start.

Sometimes seeking at all will trigger SB to jump. (And sometimes, it doesn't skip a segment and I have to move back and forth to get it to detect the current timestamp to jump.)

Let me know if there's any information or tests I can do to help diagnose it.

**Comment by mchangrh** [comment] 2022-04-17 16:20
okay, that helped a lot. I think I know exactly what the problem is - if its only on that type of playlist that means that SB is fetching the videoID from the cached document before YT fully "switches" to a new video.

Hopefully, this should be fixed by #1278 since there is a hook for navigation changes. I'll try to get a quick PR out for you to test with just the navigation triggers.

Also w.r.t the empty profile not working, try the beta from #1273. It fixed the issue with `/playlist?list=` links not working but there hasn't been a new release yet

**Closed** 2022-12-04 20:15 UTC
