### ISSUE TITLE
[Feature Request] Option to automatically skip segments if you already fast-forwarded to a portion of the video that is in the middle of a segment

### ISSUE THREAD

**Issue by 32423d** [ajayyy/SponsorBlock#1418] opened 2022-07-28 03:41 UTC
This feature would make it so there is an option to make sponsorblock automatically skip segments if you already fast-forwarded into a portion of the video that has a segment. For example, you press the right arrow key on your keyboard and your video skips 10 seconds forward into the middle of a "Sponsor" segment. Sponsorblock then automatically skips the video forward to the end of the "Sponsor" segment. The way that sponsorblock behaves right now without the option is if you skip 10 seconds forward into the middle of a "Sponsor" segment the video continues to play without you skipping to the end of the segment. The feature I outlined in the title is already present in the NewPipe x SponsorBlock fork (https://github.com/polymorphicshade/NewPipe) but it doesn't come as an option that you can turn off.

**Comment by JohnVeness** [comment] 2022-08-13 17:28
Duplicate of #124

**Closed** 2022-08-13 17:29 UTC
