### ISSUE TITLE
[Solved] Safari extension doesn't show up in Extensions list

### ISSUE THREAD

**Issue by anijatsu** [ajayyy/SponsorBlock#827] opened 2021-07-05 08:39 UTC
Installed from
https://apps.apple.com/us/app/sponsorblock-for-youtube/id1573461917
Program version -  2.1.1 (10)
OS: macOS 11.4 on MacBook Pro (13-inch, M1, 2020)
I have restarted the browser. After e.g. installing [Tampermonkey](https://apps.apple.com/us/app/tampermonkey/id1482490089?mt=12) for the first time, I got a bar in Safari saying that there's a new extension pending my activation, without restarting the browser.

Screenshots:
<img width="800" alt="Screenshot 2021-07-05 at 10 35 01" src="https://user-images.githubusercontent.com/1882015/124442104-ae024680-dd7c-11eb-99dc-eeb1c87c88ff.png">

<img width="904" alt="Screenshot 2021-07-05 at 10 33 52" src="https://user-images.githubusercontent.com/1882015/124442037-9c20a380-dd7c-11eb-894d-256cfb58f0cc.png">

<img width="377" alt="Screenshot 2021-07-05 at 10 35 25" src="https://user-images.githubusercontent.com/1882015/124442163-beb2bc80-dd7c-11eb-97ba-fae5adcf7f91.png">

<img width="396" alt="Screenshot 2021-07-05 at 10 35 33" src="https://user-images.githubusercontent.com/1882015/124442169-bfe3e980-dd7c-11eb-8cde-c728174164fe.png">

**Comment by ajayyy** [comment] 2021-07-05 14:33
It says "Universal", not "Intel 64", so I don't think it's an ARM issue

**Comment by ajayyy** [comment] 2021-07-05 14:36
Is the issue that it isn't appearing in the list, so you can't enable it?

**Comment by anijatsu** [comment] 2021-07-05 19:16
Yup, that's the issue for me.

**Comment by ajayyy** [comment] 2021-07-05 19:20
Do you have Safari beta/tech preview installed? I know someone was having an issue with that where it was installing to only one version of Safari

**Comment by anijatsu** [comment] 2021-07-06 07:48
No, I haven't done that.
Is there a way for me to check where does Safari look for extensions?
From my own search so far I was only able to find a file that reflects the list from browser's preferences, hence it doesn't include anything related to SponsorBlock:
~/Library/Containers/com.apple.Safari/Data/Library/Safari/AppExtensions/Extensions.plist

**Comment by ajayyy** [comment] 2021-07-06 19:54
I think AppExtensions are different than WebExtensions, but I'm not 100% sure.

**Comment by WoodpeckerBaby** [comment] 2021-09-16 05:45
I have the same issue. 

<img width="230" alt="Screen Shot 2021-09-16 at 1 41 26 PM" src="https://user-images.githubusercontent.com/14303318/133556036-671621bd-7a8f-4b93-822c-ced5074d6236.png">

<img width="201" alt="Screen Shot 2021-09-16 at 1 42 03 PM" src="https://user-images.githubusercontent.com/14303318/133556086-4a697838-a48c-459a-86ea-1a96e16821c9.png">

<img width="1003" alt="Screen Shot 2021-09-16 at 1 42 19 PM" src="https://user-images.githubusercontent.com/14303318/133556135-b1299cef-2fa7-43bb-a686-1cf110a8be53.png">

Build is successful, but the button doesn't click. 

Enable unsigned extension checked, but the extension doesn't appear in the list. 

<img width="1226" alt="Screen Shot 2021-09-16 at 1 43 46 PM" src="https://user-images.githubusercontent.com/14303318/133556346-ba1e3bd7-8f77-4f6b-9b29-547c7720a191.png">

Restarting safari to try it again didn't work.

**Comment by su-thomas** [comment] 2021-09-16 12:27
I'm having the same issue on macOS 10.15.7 (19H1323)

**Comment by ajayyy** [comment] 2021-09-17 03:38
@WoodpeckerBaby For building manually, check the bundle identifier (see https://github.com/ajayyy/SponsorBlock/wiki/Safari#publishing) and make sure it lines up with the package name in the code (it is in one of the swift files).

**Comment by ajayyy** [comment] 2021-09-17 03:38
@su-thomas manual, or through app store?

**Comment by su-thomas** [comment] 2021-09-17 04:37
> @su-thomas manual, or through app store?

manual

**Comment by WoodpeckerBaby** [comment] 2021-09-17 15:41
> @WoodpeckerBaby For building manually, check the bundle identifier (see https://github.com/ajayyy/SponsorBlock/wiki/Safari#publishing) and make sure it lines up with the package name in the code (it is in one of the swift files).

I got this when running the command `xcrun safari-web-extension-converter /path/to/extension`, not sure if this matters

> Warning: The following keys in your manifest.json are not supported by your current version of Safari. If these are critical to your extension, you should review your code to see if you need to make changes to support Safari:
> 	declarativeContent

**Comment by su-thomas** [comment] 2021-09-24 11:28
@ajayyy issue seems to be resolved after updating to Safari 15.0 (15612.1.29.41.4, 15612)

**Comment by jesusdeveloper** [comment] 2021-09-24 23:45
Hi!

I have seen the post but I see that the solution is to upgrade to Safari 15.
I have the version: Version 15.0 (16612.1.29.41.4, 16612)
And it does not work :(

**Comment by WoodpeckerBaby** [comment] 2021-09-25 11:56
Okay, the free app in App Store now works again in Safari 15.

**Comment by jesusdeveloper** [comment] 2021-09-25 12:54
> Okay, the free app in App Store now works again in Safari 15.

I´ve downloaded free version to AppStore and it works great in M1!!!
Thank you!!!

**Comment by ajayyy** [comment] 2021-09-25 13:34
Which one is this?

**Comment by WoodpeckerBaby** [comment] 2021-09-27 08:59
> Which one is this?

https://apps.apple.com/ca/app/sponsorblock-port-for-youtube/id1532163541

**Comment by ajayyy** [comment] 2021-09-27 16:12
weird, because one of the reasons I published mine is people saying that one didn't work on m1.

**Comment by ItsEcholot** [comment] 2021-11-09 09:27
I just bought the official AppStore version and it doesn't show up with Safari 15.1

**Comment by ajayyy** [comment] 2021-11-10 23:22
by the way, if anyone bought the App Store version and can't get it working even though it is too late for a refund through Apple, feel free to email me to try to refund it another way.

**Comment by ajayyy** [comment] 2021-11-10 23:23
I'm going to republish it tonight, which uses Apple's new extension format, hopefully that fixes it

**Comment by Rediwed** [comment] 2021-11-11 08:30
> I'm going to republish it tonight using Apple's new extension format, hopefully that fixes it

Thanks, hopefully that fixes it. I will delete helper app until then.

**Comment by Rediwed** [comment] 2021-11-25 09:14
> I'm going to republish it tonight using Apple's new extension format, hopefully that fixes it

Hi @ajayyy, did you have the time to look into republishing the extension in the new format? It’s still not showing up in Safari for me.

**Comment by ajayyy** [comment] 2021-11-25 14:34
I did but apple still hasn't approved it

**Comment by Rediwed** [comment] 2021-11-25 14:35
Classic, haha. I’ll wait anxiously. Thank you!

**Comment by ShivamJoker** [comment] 2021-12-14 06:42
> I did but apple still hasn't approved it

@ajayyy bought the extension but isn't showing up 😢

**Comment by ajayyy** [comment] 2021-12-14 06:44
Darn, very weird since I use their official converter and haven't changed too much of the Safari swift ckde. It's off that I can't find anyone else having this issue with other extensions

**Comment by ShivamJoker** [comment] 2021-12-14 06:46
Can it be because of OS upgrade to Monterey 12.0.1 ?

**Comment by ajayyy** [comment] 2021-12-14 06:48
I've been building and testing on Monterey

**Comment by ShivamJoker** [comment] 2021-12-14 06:50
Have look I will try to build it and let you know if it works or not
https://user-images.githubusercontent.com/23727670/145947449-120e4029-538b-4a70-9e0e-0c78ef158ee6.mov

**Comment by ShivamJoker** [comment] 2021-12-14 07:00
@ajayyy even after manually building the latest version it doesn't show up

**Comment by su-thomas** [comment] 2021-12-21 08:49
I believe I have found a fix for this.

From what I can gather, this issue of the extension not appearing in Safari's extension list is not caused by anything wrong with the SponsorBlock extension. It seems to be caused by corruption of macOS' LaunchServices database.

After rebuilding my LaunchServices database, it resolved issues I was having with this extension not appearing in the list. It also resolved the issue for other extensions I was having the same issue with.

I stumbled across this fix in this [issue thread for Bitwarden](https://github.com/bitwarden/browser/issues/1718), which is another Safari extension.

In order to reuild the LaunchService database, you can either run a command or use the [OnyX](https://www.titanium-software.fr/en/onyx.html) tool.

I found that there is some debate in [this blog](https://eclecticlight.co/2017/08/11/launch-services-database-problems-correcting-and-rebuilding/) about how extensive the rebuild scope should be. I think it is better to keep a smaller scope, to avoid aggressively rebuilding other parts of the database.

Unfortunately due to my inability to reproduce the issue, I cannot do any testing to figure out the minimal scope required for the rebuild command.

So I will share which command I used, but do feel free to read that blog post and try using some of the more minimal scopes first perhaps.

Command I used to rebuild the LaunchServices database to fix this issue: `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain u -domain s -domain l -seed`

**Comment by ShivamJoker** [comment] 2021-12-21 09:59
Gosh this worked 😄 
Thanks a lot @su-thomas 

@ajayyy do you have any plans on updating the UI of app ?

**Comment by Rediwed** [comment] 2021-12-21 10:42
@su-thomas Wow, nice! Within a minute or so after running this command the extension showed up in Safari. It worked really greatly! I also noticed that it fixes another extension; [SafariKeywordSearch](https://github.com/arnemart/SafariKeywordSearch#safarikeywordsearch) by @Arnemart

**Comment by su-thomas** [comment] 2021-12-21 11:00
> @su-thomas Wow, nice! Within a minute or so after running this command the extension showed up in Safari. It worked really greatly! I also noticed that it fixes another extension; [SafariKeywordSearch](https://github.com/arnemart/SafariKeywordSearch#safarikeywordsearch) by @Arnemart. So can this bug occur for any Safari extension, or is there a common denominator between them?

Glad to hear it fixed the issue!
I think it can occur with any Safari extension. It also seems LaunchServices is responsible for several other parts for macOS, such as default apps, and rebuilding it is a common fix.

**Comment by Rediwed** [comment] 2021-12-21 12:17
We should probably file feedback with Apple about this.

**Comment by ajayyy** [comment] 2021-12-21 16:27
@ShivamJoker Good idea, I'll add a link to this comment in the main screen of the app.

**Comment by ajayyy** [comment] 2022-01-04 21:19
Update pushes

**Closed by ajayyy** 2022-01-04 21:19 UTC
Labels: Safari

**Comment by Eloren1** [comment] 2025-03-08 06:01
This is still a problem, and that solution did not work

**Comment by Eloren1** [comment] 2025-03-08 06:30
For me it worked after re-enable "Show features for web developers" and then re-enable "Allow unsigned extensions"
