### ISSUE TITLE
Feature request: Per-channel configuration of Disabled/Auto-skip/etc.

### ISSUE THREAD

**Issue by cheintz** [ajayyy/SponsorBlock#1833] opened 2023-08-16 16:28 UTC
Each user will have varying opinions of which channels do an acceptable amount of, e.g., self promotion. In the same way that users may want to whitelist individual creators, they may wish to whitelist particular segments for particular creators.

**Comment by mchangrh** [comment] 2023-09-06 19:06
dupe of #435

**Closed** 2023-09-06 21:24 UTC
