### ISSUE TITLE
Add a pop-up that will warn that the video is completely promotional

### ISSUE THREAD

**Issue by usera123ewqfd1234** [ajayyy/SponsorBlock#1057] opened 2021-11-25 19:15 UTC
Please make some pop-up window that will warn you that the video is completely advertising, and make possible disable this window in the settings of SponsorBlock.

**Comment by ajayyy** [comment] 2021-11-25 19:16
Duplicate of https://github.com/ajayyy/SponsorBlock/issues/182

**Closed by ajayyy** 2021-11-25 19:16 UTC
