### ISSUE TITLE
Info button animation sometimes choppy on Firefox

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#811] opened 2021-06-26 17:33 UTC
The animation sometimes doesn't play.

***

> I think I found a fix, after removing 
> ```css
> .playerButton.hidden {
>     display: none;
> }
> ```
> from line 90 to 92 in content.css the animation now works properly

https://cdn.discordapp.com/attachments/603643256714297374/858396929297743922/SB_css.mp4

from Kraii https://discord.com/channels/603643120093233162/603643256714297374/858396056630460457

**Comment by lord-blex** [comment] 2021-12-10 16:51
The discord thread mentions that this was supposed to solve #810. Is that why it's still like this, or did just no one get around to removing it?
I installed Enhancer on Firefox and Edge and could not reproduce #810 with or without this css.

And it's not even used in all cases:
Edge seems to ignore it in favor of `.ytp-chrome-controls .ytp-button`.
And after opening and closing the popup `style="display: unset;"` is added to the element, so the css is ignored from then on.

**Comment by ajayyy** [comment] 2021-12-10 17:02
It is supposed to hide it right after the animation is finished. The issue might be that the 10ms timing might be wrong of different browsers, or maybe also on slower computers.

https://github.com/ajayyy/SponsorBlock/blob/44de741e84eb8ab6fbc17b8b465a2aec184d79ec/src/utils.ts#L186-L228

Skip to highlight does properly resize for me on Chrome. You can see the chapter text move back there is not an empty space between the button and the chapter text.

![resizing skip to highlight](https://user-images.githubusercontent.com/12688112/145612742-3758dea9-4aa0-43c7-8c91-584be36fd160.gif)

**Comment by lord-blex** [comment] 2021-12-10 18:34
Skip to highlight doesn't have the playerButton class, and it has display:block from its ID, so it's never actually hidden. Only the css transition hides/shows it.
If I remove the lines in the op from content.css, then the Info button acts the same as the Skip to highlight button.

**Comment by ajayyy** [comment] 2021-12-11 00:10
Removing css seems to work fine enough and doesn't seem to break anything else.

![info button enhancer](https://user-images.githubusercontent.com/12688112/145655942-0cea6653-1026-4969-8072-91462795f6c2.gif)

**Closed** 2021-12-11 00:09 UTC
Labels: bug, help wanted

**Comment by ajayyy** [comment] 2021-12-11 00:13
I think it was left over code from before I figured out how to get the animation to slowly shrink the width.
