### ISSUE TITLE
Add LBRY

### ISSUE THREAD

**Issue by erkinalp** [ajayyy/SponsorBlock#1385] opened 2022-06-30 14:00 UTC
Decentralised protocol to share content using blockchain.

Applicable categories: 
- all (video&audio)
- sponsor, self promotion, exclusive access, interaction reminder, preview (other content)

**Comment by mchangrh** [comment] 2022-06-30 18:58
duplicate of #515, #654 and #972

**Closed** 2022-06-30 19:42 UTC

**Comment by stefanmm** [comment] 2022-09-28 09:07
I made a simple plugin that loads and skips sponsored segments on YouTube videos imported to Odysee -  https://github.com/stefanmm/sponsorblock-odysee
It is very basic for now, so feel free to improve it.
