### ISSUE TITLE
[feature request] jump scare segment

### ISSUE THREAD

**Issue by aledbet3** [ajayyy/SponsorBlock#1232] opened 2022-03-16 20:09 UTC
request to add segment type for jump scares

**Comment by Rajdave69** [comment] 2022-03-17 14:16
Good Idea! Should be toggled off by default tho!

**Comment by mchangrh** [comment] 2022-03-18 20:30
duplicate of https://github.com/ajayyy/SponsorBlock/issues/702

**Closed** 2022-03-18 20:37 UTC
