### ISSUE TITLE
High CPU usage on Youtube Music

### ISSUE THREAD

**Issue by rohmishra** [ajayyy/SponsorBlock#1034] opened 2021-11-08 03:23 UTC
Having the extension enabled on Firefox while listening to YTM results in significant CPU usage by extension.

Firefox Profiler:
https://share.firefox.dev/3CVLctC

**Comment by ajayyy** [comment] 2021-11-08 03:25
duplicate of #501

**Closed by ajayyy** 2021-11-08 03:25 UTC

**Comment by rohmishra** [comment] 2021-11-08 03:26
Thanks! I dont know how i missed that, Its been a long day maybe i should really go to sleep now :P
