### ISSUE TITLE
Prevent autoplay while segment creation

### ISSUE THREAD

**Issue by Vee-Jay** [ajayyy/SponsorBlock#842] opened 2021-07-13 06:19 UTC
Disable autoplay to next video in playlist if there are any segments that needs to be uploaded. 
This is needed as for properly marking an end credit till end of the video. Currently it changes to next video on list and while returning to the video, the markers are lost.

**Comment by Vee-Jay** [comment] 2021-07-13 07:06
Can implement auto pause on last frame if new segments are being created and if there are segments that are not submitted. 

https://github.com/NDevTK/AutoPause

**Comment by mchangrh** [comment] 2022-04-11 06:24
duplicate of #384

**Closed** 2022-04-11 06:25 UTC
