### ISSUE TITLE
[Feature] PeerTube Support

### ISSUE THREAD

**Issue by seniorm0ment** [ajayyy/SponsorBlock#993] opened 2021-10-08 09:27 UTC
Requesting the ability for PeerTube Sponsorblock support.

**Comment by ccuser44** [comment] 2021-10-14 06:38
Never seen sponsors on peertube.

**Comment by ajayyy** [comment] 2021-10-14 22:11
duplicate of https://github.com/ajayyy/SponsorBlock/issues/515

**Closed by ajayyy** 2021-10-14 22:11 UTC
