### ISSUE TITLE
Add Floatplane

### ISSUE THREAD

**Issue by erkinalp** [ajayyy/SponsorBlock#1383] opened 2022-06-30 13:50 UTC
A tech-focussed subs-only video network.

Applicable categories: Self-promotion, exclusive access, preview, technical mishap, intro, highlight, outro

**Comment by mchangrh** [comment] 2022-06-30 18:59
duplicate of #515 - **please** keep discussion in one place instead of cross posting it 3 times in hopes of getting some sort of immediate response

**Closed** 2022-06-30 19:41 UTC
