### ISSUE TITLE
Welcome page doesn't follow browser language

### ISSUE THREAD

**Issue by Elaborendum** [ajayyy/SponsorBlock#876] opened 2021-08-05 05:46 UTC
![imagen](https://user-images.githubusercontent.com/71190696/128297394-532b3b30-98f3-497f-a492-c91ba382f9fa.png)

This is the page that pops up when you install the extension, giving you an introduction to it. The main text on the page isn't translated, but the options are. However, according to the Crowdin page, it says that the addon is fully translated to Spanish.

**Comment by ajayyy** [comment] 2021-08-05 05:47
Duplicate of https://github.com/ajayyy/SponsorBlock/issues/509

**Closed by ajayyy** 2021-08-05 05:47 UTC
