### ISSUE TITLE
[Bug] SponsorBlock does not work in miniplayer.

### ISSUE THREAD

**Issue by supernoodled** [ajayyy/SponsorBlock#944] opened 2021-09-15 14:41 UTC
Using Firefox 92.0 (latest version) with uBlock Origin, Universal Bypass, Mega, HTTPS Everywhere, Decentraleyes, Nano Defender for Firefox, and SponsorBlock.

Everything works fine until you try the miniplayer. If you are able to open the miniplayer while say an intro is playing, SponsorBlock works fine and will ask if you want to skip the intro (my setting). After that, it will fail to skip the sponsors.

**Comment by nishant-ranjan28** [comment] 2021-09-16 14:22
yes, I observed the same issue. Thanks for creating it.

**Comment by SameenAhnaf** [comment] 2022-01-26 10:50
@ajayyy Duplicate of #707

**Closed** 2022-01-26 13:09 UTC
