### ISSUE TITLE
[Feature request]Speedup as an alternative to skipping

### ISSUE THREAD

**Issue by sasasqt** [ajayyy/SponsorBlock#1349] opened 2022-06-06 15:18 UTC
playbacks blocks at user-controlled speed(for example:2x) as an alternative.

**Comment by SameenAhnaf** [comment] 2022-06-07 02:07
Duplicate of https://github.com/ajayyy/SponsorBlock/issues/499

**Closed** 2022-06-07 02:19 UTC
