### ISSUE TITLE
Embedded playlist show non-existant segment

### ISSUE THREAD

**Issue by FlorianZahn** [ajayyy/SponsorBlock#959] opened 2021-09-20 16:08 UTC
[Discorvered here](https://discord.com/channels/603643120093233162/603643180663177220/889519645302857728)

This can lead to videos being skipped completely and the next one being played without a chance to watch the first video.

The embedded URL was https://www.youtube.com/embed/videoseries?list=PL91WMVRthH5aXTgfdox3waSIK75cBDl9l
Switching videoseries to playlist solved it, i.e. 
https://www.youtube.com/embed/playlist?list=PL91WMVRthH5aXTgfdox3waSIK75cBDl9l

This is mostly for people searching for a fix for this specific issue.

**Comment by JMdoubleU** [comment] 2021-10-02 19:15
Here is the segment that's wrongly associated with that example videoseries:

```json
{
  "videoID": "videoseries",
  "hash": "c268dee0d84687a3e03d4588fb350b44c6da408f33210dda80e53b7f654f8d37",
  "segments": [
    {
      "category": "interaction",
      "actionType": "skip",
      "segment": [
        9376.475,
        9499
      ],
      "UUID": "51832309e1547a0adb4f6a17cb0a6a324feb8a5dfe21bb580d7cf94de4db0787",
      "videoDuration": 0
    }
  ]
}
```

**Comment by ajayyy** [comment] 2021-10-02 19:25
Interesting that the url can contain anything

https://www.youtube.com/embed/randomGarbageText?list=PL91WMVRthH5aXTgfdox3waSIK75cBDl9l works

**Comment by ajayyy** [comment] 2021-10-02 19:27
The issue is probably just that `videoseries` happens to be 11 characters, so the extension assumes it must be a  valid videoID.

**Comment by ajayyy** [comment] 2022-01-06 21:53
Fixed by https://github.com/ajayyy/SponsorBlock/pull/1116

**Closed by ajayyy** 2022-01-06 21:53 UTC
