### ISSUE TITLE
3rd-party YT sites not supported on Firefox for Android

### ISSUE THREAD

**Issue by cazwacki** [ajayyy/SponsorBlock#1643] opened 2023-01-10 13:41 UTC
After installing the extension on an Android browser, the add-on cannot request additional permissions. Thus the 3rd-party Youtube-Sites option cannot be enabled.

**Comment by ajayyy** [comment] 2023-01-10 19:10
Firefox for Android does not implement optional permissions

**Comment by cazwacki** [comment] 2023-01-10 19:19
Can a custom version of SponsorBlock exist with host permissions for all sites?

**Comment by mchangrh** [comment] 2023-01-18 03:06
duplicate of #1462 implemented in #1469

**Closed** 2023-01-18 16:53 UTC
