### ISSUE TITLE
Segments have not been showing on the default Invidious player for months.

### ISSUE THREAD

**Issue by SkMyPP** [ajayyy/SponsorBlock#1306] opened 2022-05-07 02:00 UTC
This isn't a problem with the "YouTube style" player, but the problem is that the YouTube style player is that it's absolutely asinine, ugly and is literally broken.

**Comment by mchangrh** [comment] 2022-05-09 06:34
duplicate of #1294 

if you have a problem with the youtube style player, I suggest you bring it up on their repository https://github.com/iv-org/invidious

**Closed** 2022-05-09 17:31 UTC
