### ISSUE TITLE
Video loops instead of ending (bug)

### ISSUE THREAD

**Issue by kwinz** [ajayyy/SponsorBlock#1409] opened 2022-07-19 11:24 UTC
This video:
https://www.youtube.com/watch?v=hg4l5vuqHXc

ends with a "sponsor" segment followed by "endcard/credits" which I have set to skipp.

```
Sponsor
0:00.000 to 0:07.153
Sponsor
7:42.837 to 8:54.464
Endcards/Credits
8:54.464 to 9:02.101
```

Instead of ending the video as soon as the sponsor segment is reached the video starts playing for the start again.
I have not enabled "loop" setting in Youtube player.

This seems to be a bug with Sponsorblock. I have version `4.6.3` installed in Chrome `Version 103.0.5060.114 (Official Build) (64-bit)`

**Comment by ajayyy** [comment] 2022-07-20 03:39
I cannot reproduce the issue

**Comment by mchangrh** [comment] 2022-07-21 20:16
might be related to #1240

**Comment by ajayyy** [comment] 2023-10-18 23:57
I believe this will be fixed by https://github.com/ajayyy/SponsorBlock/commit/c8c141f5c9f0082863d9c3304c0cad17fe394b84

**Closed by ajayyy** 2023-10-18 23:57 UTC

**Comment by kwinz** [comment] 2023-11-01 17:10
I am not sure when it was fixed exactly, but I just retested with v. 5.4.25 and the issue is gone. Thanks for your support!
