### ISSUE TITLE
SponsorBlock disappeared from Safari extension list

### ISSUE THREAD

**Issue by Rediwed** [ajayyy/SponsorBlock#1038] opened 2021-11-10 20:49 UTC
Not sure what happened, but SponsorBlock flat-out disappeared from my Safari extension list. Removing and re-installing it does not seem to work. Also, clicking the 'Quit and Open Safari Extensions Preferences…’ button in the SponsorBlock helper-app doesn’t do anything. It doesn’t open Safari’s extensions nor does it quit the helper app.

Not sure how to debug this one..

**Comment by ajayyy** [comment] 2021-11-10 23:20
Duplicate of https://github.com/ajayyy/SponsorBlock/issues/827

There are a few ideas there

**Closed by ajayyy** 2021-11-10 23:20 UTC
