### ISSUE TITLE
Work In Sites Not Embeding YouTube

### ISSUE THREAD

**Issue by Champe20** [ajayyy/SponsorBlock#1781] opened 2023-06-21 15:09 UTC
Is there a possibility to make SponsorBlock work on sites such as FloatPlane, PeerTube instances by manually enabling it per-site and detecting when a video was playing? It could then search for a video named the same on YouTube using Newleaf and both be able to use the sponsor segments and send them. It seems like it wouldn't be too hard to add support for reading segments on those sites, the hard part would be actually skipping them and writing them.

**Comment by mchangrh** [comment] 2023-06-26 07:25
duplicate of #1335

**Closed** 2023-06-26 19:11 UTC
