### ISSUE TITLE
[Feature request] Add category for seizure-inducing scenes

### ISSUE THREAD

**Issue by hifinerd** [ajayyy/SponsorBlock#1059] opened 2021-11-26 20:02 UTC
Right now, warnings for epilepsy on youtube videos are inconsistent and janky, and some videos may not even have epilepsy warnings at all, so I believe there should be a category to skip scenes that may trigger epilepsy.

**Comment by mchangrh** [comment] 2021-11-27 16:36
duplicate of https://github.com/ajayyy/SponsorBlock/issues/403

**Closed** 2021-11-27 17:11 UTC
