### ISSUE TITLE
Support for YouTube TV URLs in extension

### ISSUE THREAD

**Issue by DraconicNEO** [ajayyy/SponsorBlock#1216] opened 2022-03-04 23:27 UTC
Hello I think it would be a good idea to implement support for the YouTube TV version of the site
(`youtube.com/tv`) since it doesn't seem to support it at the moment.

While many may not know this, it is in fact still possible to still access YouTube TV in chrome and Firefox using these two browser extensions [YouTube Smart TV (Firefox)](https://addons.mozilla.org/en-US/firefox/addon/youtube-for-tv/) and [YouTube for TV (chrome)](https://chrome.google.com/webstore/detail/youtube-for-tv/gmmbpchnelmlmndfnckechknbohhjpge).

**Comment by ajayyy** [comment] 2022-03-05 00:06
Duplicate of https://github.com/ajayyy/SponsorBlock/issues/213

**Closed by ajayyy** 2022-03-05 00:06 UTC
