### ISSUE TITLE
Support for custom chapters

### ISSUE THREAD

**Issue by SameenAhnaf** [ajayyy/SponsorBlock#784] opened 2021-06-11 21:00 UTC
It would have been great if viewers could add chapters by themselves. I know, that's not how Sponsorblock works at least currently. But it is quite related to its purpose.

Sponsorblock helps us immensely by avoiding unnecessary content and choose what to watch and what not to. Unfortunately, all uploaders  don't add chapters to their videos and this makes the experience more frustrating than ever.
 
1. Users will be able to stream exactly what they want.
2. Especially useful for long informative videos. These videos take up a lot of data while seeking.
3. No need to be dependent on what uploader wants to feed you.
4. Know about each segment separately in a better way (where they start, how long I will watch, alignment of topics etc.)

Note that this support should be only for videos with no chapter at all as uploaders will be always precise about the contents.

**Comment by ajayyy** [comment] 2021-06-11 21:02
Duplicate of https://github.com/ajayyy/SponsorBlock/issues/409

**Closed by ajayyy** 2021-06-11 21:02 UTC
