### ISSUE TITLE
SponsorBlock not working on Youtube. Cannot identify video. Not blocking sponsors.

### ISSUE THREAD

**Issue by ScarletMcLearn** [ajayyy/SponsorBlock#2006] opened 2024-04-19 08:29 UTC
Not working on Youtube. Cannot identify video.

![image](https://github.com/ajayyy/SponsorBlock/assets/17823921/0dc01640-20c1-48c7-b2ee-ee105a022e01)

https://pasteboard.co/b6Ym9L7dIqiL.png

**Comment by Leah96xxx** [comment] 2024-04-19 13:35
Confirmed I also have this issue. Refreshing the tab does nothing, and refreshing the extension will find the video but fail to skip sponsors.

**Comment by ajayyy** [comment] 2024-04-19 19:40
still doing this?

**Comment by PasttaTypo** [comment] 2024-04-19 20:14
> still doing this?

Yeh, I've had a few 504 Connection Errors and segments not loading in after refreshing randomly. I do know my submissions haven't been visible on the SB Browser since yesterday.

**Comment by ajayyy** [comment] 2024-04-19 21:51
504 is different, I mean it saying "No video found"

**Comment by Leah96xxx** [comment] 2024-04-20 05:48
Still saying "No video found" for me. Extension appears to be up to date

**Comment by ajayyy** [comment] 2024-04-20 05:52
Is this a new issue, or did you recently install the extension?

**Comment by Leah96xxx** [comment] 2024-04-20 05:55
It's a new issue. I've had Sponsor Block installed for months.

Just restarted my browser altogether and it seems to be fixed now.

**Comment by ScarletMcLearn** [comment] 2024-04-20 06:00
I restarted my browser - Edge, Chrome - but still not fixed.

**Comment by BigBOSSo** [comment] 2024-04-22 10:24
Same thing for a few days. Google chrome

![image](https://github.com/ajayyy/SponsorBlock/assets/19314407/70ee6ce2-8a30-4466-822c-84f969262c00)

**Comment by ScarletMcLearn** [comment] 2024-04-24 06:02
Same here. No change.

**Comment by ajayyy** [comment] 2024-04-29 01:35
>  I've had a few 504 Connection Errors

This is different and is a server issue

**Closed** 2024-04-29 01:36 UTC

**Comment by ScarletMcLearn** [comment] 2024-05-11 18:46
This is still not working

**Comment by itsmevictor** [comment] 2024-07-05 06:18
I have the same issue: "Segments still loading". 

Otherwise, thank you for the great extension :-)
