### ISSUE TITLE
Text contrast issues when using an Invidious instance and submitting segments

### ISSUE THREAD

**Issue by JacksonChen666** [ajayyy/SponsorBlock#1412] opened 2022-07-22 19:06 UTC
When submitting segments (or more accurately, pressing the shortcut for "Submit segments"), the text for category selection and segment type selection is dark, making it very difficult to read the text.
This only affects drop down lists for category and segment type (skip, mute, etc.) on third party instances like Invidious and not on YouTube.

- [On an Invidious instance with dark reader OFF](https://user-images.githubusercontent.com/50755746/180505818-9f029523-c48d-475e-8b64-7f787fe0c265.png)
- [On an Invidious instance with dark reader ON](https://user-images.githubusercontent.com/50755746/180505824-674ed08f-db67-4f8b-8db7-424c942995ff.png)
- [On YouTube with dark reader OFF](https://user-images.githubusercontent.com/50755746/180506123-b0c80ff8-4d87-470b-a043-16a88e2bb4b0.png)
- [On YouTube with dark reader ON](https://user-images.githubusercontent.com/50755746/180506111-da7e7464-a586-4a07-90aa-be9301099706.png)

(also another bug i'm really not bothered to report separately: when submitting segments on invidious, there is a horizontal browser scroll bar that blocks the 4 manipulation buttons (edit, delete, etc.) when there's only 1 segment, preventing the use of the buttons until the horizontal scroll bar hides)

**Comment by mchangrh** [comment] 2022-07-24 12:10
Duplicate of https://github.com/ajayyy/SponsorBlock/issues/952 ?

**Comment by JacksonChen666** [comment] 2022-07-24 12:29
pretty much #952 i guess

**Closed** 2022-07-24 15:22 UTC
