### ISSUE TITLE
A connection error has occurred. Error code: undefined

### ISSUE THREAD

**Issue by CharAznableLoNZ** [ajayyy/SponsorBlock#1551] opened 2022-10-23 01:23 UTC
Every YT video I load has this error occur.  Due to this, no segments are skipped.  Running on FF 105.0.1.
Workaround:
Pause video
Click sponsorblock extension and click the refresh button on it.
It takes 15 or so seconds then loads the segments.
The segments are skipped as expected.
Expected:
It just works like it used to.

I saw there were some connectivity issues with submitting segments, is this related?

**Comment by CharAznableLoNZ** [comment] 2022-10-23 01:25
I would rather the video hang on playing until the extension has finished loading segments.

**Comment by mchangrh** [comment] 2022-10-23 05:01
duplicate of #1549

**Closed** 2022-10-23 15:03 UTC
