### ISSUE TITLE
[Feature Request] - Standardize certain intro section to skip based on channels.

### ISSUE THREAD

**Issue by dpthegrey** [ajayyy/SponsorBlock#1102] opened 2021-12-21 04:18 UTC
I am proposing a feature request by which we can define that "x" channel has it's intro for "i" to "j" time which remains constant and almost not required to change for a while. 

For example: in the start or they have outro which goes on to every new video they post/upload. Same Intro goes at same time. How about having that part saved so whenever we go to their newly uploaded video we don't need to manually set the intro animation and things like that which we already know exist but someone hasn't submitted yet. 

I apologize it the same issue exist. I haven't read all of the issues but certainly an active member can suggest what to do. Thanks

**Comment by mchangrh** [comment] 2021-12-21 06:36
duplicate of #799

**Closed** 2021-12-21 16:23 UTC
