### ISSUE TITLE
Scrollbars when you have SponsorBlock on overflow menu in Firefox.

### ISSUE THREAD

**Issue by Nojuuu** [ajayyy/SponsorBlock#778] opened 2021-06-06 23:06 UTC
### Description
There is scrollbars when you put SponsorBlock to Overflow menu in Firefox.

![image](https://user-images.githubusercontent.com/84513173/120942837-1df8bf00-c734-11eb-98c7-e29b465b660a.png)

### Steps to Reproduce

1. Put SponsorBlock addon to overflow menu in Firefox.
2. Click to open it

### Expected Behavior

No scrollbars.

**Comment by AronHK** [comment] 2021-12-13 13:29
Popups in the overflow menu are given a fixed width, seems like it's 350px.
So the SponsorBlock popup should be able to scale to that.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#popup_resizing

**Comment by Nojuuu** [comment] 2021-12-20 07:51
Since nothing really requires scrolling in that popup at the moment, you could probably just set `overflow: hidden` for `#sponsorBlockPopupBody` to fix it for now?

**Comment by AronHK** [comment] 2021-12-20 15:51
But only vertically, so technically <code>overflow-x</code> could be used. But that causes it to be off-center, so I don't think that's a good solution.
Changing the widths works, but that also changes the "popup" shown on the youtube page, so that's probably not great either. If I understand correctly #1017 makes the two popups different components, so it could be changed with/after that.

This seems to work well for me in popup.css:
```
#sponsorBlockPopupBody {
  margin: auto; 
  width: 340px; 
  background: var(--sb-main-bg-color);

  color-scheme: dark;
}

#sponsorblockPopup {
  color: var(--sb-main-fg-color);
  font-family: 'Source Sans Pro', sans-serif;
  font-size: 14px;
  display: flex;
  flex-flow: column nowrap;
  align-items: center;
  padding: 22px;
  text-align: center;
  margin-bottom: var(--ytd-margin-6x);
}
```

**Comment by Nojuuu** [comment] 2021-12-20 16:30
> It does require scrolling when there are segments shown

True, I tried to play around with the popup css, but I wasn't on YouTube, so I forgot about those.

**Comment by Nojuuu** [comment] 2021-12-22 11:52
@ajayyy 

What if you just do:

```css
@media only screen and (max-width: 348px) {
  #sponsorBlockPopupBody, #sponsorBlockPopup {
  max-width: fit-content;
  }
}
```

**Comment by Nojuuu** [comment] 2022-03-19 20:16
It also doesn't seem to scale well on mobile.

![Screenshot_20220319-221130](https://user-images.githubusercontent.com/84513173/159136982-cb2a8b35-a4fd-4af5-85a4-4c971fea2b77.jpg)

**Comment by ajayyy** [comment] 2022-03-19 20:17
I think this was fixed by https://github.com/ajayyy/SponsorBlock/pull/1228

**Comment by AronHK** [comment] 2022-03-19 20:27
nope, I just built the latest version and it's still bad. 
![image](https://user-images.githubusercontent.com/9072794/159137178-f7bc87c6-1cd7-42c1-aa2f-d22515be05df.png)

I wrote a fix a while ago but didn't submit it because I was also messing around with #522 for a complete Firefox-fix-package. The css changed a bit since then so I would have to look again to see if what I wrote is still compatible.

**Comment by AlecRust** [comment] 2022-03-19 21:23
The "scale well on mobile" part you mention should be fixed by #1228 which is not yet released.

Regarding horizontal scrollbar I've tested this inside and outside the Overflow Menu. I see it's slightly different for others, but for me, the horizontal scrollbar only appears under these conditions (macOS Firefox 98.0.1):
- Extension is positioned _outside_ the Overflow Menu
- "Whitelist channel" is clicked which pushes content down and causes a reflow

It appears the page goes behind the vertical scrollbar, and the amount you can horizontally scroll is the width of the vertical scrollbar. Looks like it may be [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1395025).

I'd be inclined to "fix" this for now with `overflow-x: auto` which produces the "slightly off centre" result of:

![image](https://user-images.githubusercontent.com/247634/159138570-43ec3ce7-1106-46a7-b34d-19c4ea993467.png)

I've included this change in #1237. Would you mind giving it a test using the latest artifact from that PR?

**Comment by AronHK** [comment] 2022-03-19 21:51
I think it's different because your overflow menu seems ~25px wider than mine and what's in the OP. it might be a weird os-difference.
regardless, your change got rid of the scrollbar, but now the content is quite a bit off-center.
![image](https://user-images.githubusercontent.com/9072794/159139274-104d10dc-d23c-4017-b1e0-2acd558acad5.png)

[this](https://github.com/AronHK/SponsorBlock/commit/5e8faa11c13e8128566b6b6e996a1a754fa83ad9) fixed that for me when I last tried.

**Comment by AlecRust** [comment] 2022-03-19 22:25
> but now the content is quite a bit off-center

From your two screenshots it looks like the addition of `overflow-x: auto` doesn't make it _more_ off-centre, it's just that you can no longer scroll horizontally, is that right?

> [this](https://github.com/AronHK/SponsorBlock/commit/5e8faa11c13e8128566b6b6e996a1a754fa83ad9) fixed that for me when I last tried.

That gives me a gap where the scrollbar would be:

![image](https://user-images.githubusercontent.com/247634/159139863-bf67f8d3-b898-45c1-9985-62cd08338234.png)

I'll keep poking this, but considering the OS differences you may be best placed to find the fix that works for you. I would do this on top of changes in #1237 though.

**Comment by AronHK** [comment] 2022-03-19 22:53
> doesn't make it more off-centre, it's just that you can no longer scroll horizontally, is that right?

correct. it's just more noticeable (to me) because of the missing scrollbar. but of course the scrollbar is also a very noticeable annoyance.

**Comment by Nojuuu** [comment] 2022-03-20 00:43
```css
@media only screen and (max-width: 350px) {
  #sponsorBlockPopupBody,
  #sponsorBlockPopup {
    max-width: 100%;
  }

  #sponsorBlockPopupHTML {
    padding: 10px 0px 60px 0px;
  }
}

```

@AlecRust How about that?

**Comment by AlecRust** [comment] 2022-03-20 11:52
Thanks both for your ideas. I've had another play with this and the fix seems as simple as `max-width: 100%` on `#sponsorBlockPopupBody`. No need for media queries or hiding the scrollbars with overflow.

I've tested on Windows 11 Firefox 98:

- When **outside** the overflow menu the width is the standard 374px.
  - When "Whitelist channel" is clicked which increases height, the `max-width` allows `#sponsorBlockPopupBody` to reduce in width slightly to make room for the scrollbar, just like on Chrome.
- When **inside** the overflow menu (which is strangely narrow on Windows) the `max-width` allows the `#sponsorBlockPopupBody` to reduce in width to the restricted 350px.
  - When "Whitelist channel" is clicked which increases height, I get no vertical scrollbar the popup just increases in height.

https://user-images.githubusercontent.com/247634/159160129-e3933c45-c54e-4f8c-a6a3-57c9c0339d92.mp4

I've now pushed this change to #1237, would you mind testing again using the latest artifact i.e. [this(https://github.com/ajayyy/SponsorBlock/suites/5727464817/artifacts/189511558)?

**Comment by AronHK** [comment] 2022-03-20 13:26
yeah, it works great now

**Comment by Nojuuu** [comment] 2022-03-20 16:50
Can't scroll all the way down when it gets smaller or has a lot of stuff:

![image](https://user-images.githubusercontent.com/84513173/159173085-ff9d42f1-31d8-4276-be68-158e714e9eec.png)

![image](https://user-images.githubusercontent.com/84513173/159173253-c2eadfce-ba02-4355-8de0-9f166c2c5d0f.png)

**Comment by AronHK** [comment] 2022-03-20 17:24
oh yeah, I forgot about that. I tried to find a fix for it the last time, but couldn't, besides giving it a really big bottom margin. but that looks silly when it's normal sized...

**Comment by Nojuuu** [comment] 2022-03-20 17:31
I tried to solve that with two media queries when it is shorter or taller than a certain number of pixels. But at some sizes, the scrollbar just started blinking rapidly.

**Comment by AlecRust** [comment] 2022-03-20 17:36
Regarding "when it gets smaller" I'm not sure how much of an issue this is. It looks like you reduced the height of your browser, which forced the height of the popup to reduce? That doesn't happen in my testing on Mac or Windows, it always appears over the top:

![image](https://user-images.githubusercontent.com/247634/159174783-ed862c0b-2960-492c-bfa5-f94e58adb684.png)

Regarding "has a lot of stuff" this is a separate issue really, but in my testing setting a `max-height` on the `<html>` fixes this:

![image](https://user-images.githubusercontent.com/247634/159174845-609528a2-833e-4c91-983a-44401ffcb882.png)

(I've set it to 600px max height to align with Chrome, that seems to do this automatically)

I've updated #1237 with this change, would you mind testing again using the latest artifact i.e. [this](https://github.com/ajayyy/SponsorBlock/suites/5729015035/artifacts/189621890)?

**Comment by AronHK** [comment] 2022-03-20 17:42
>I've set it to 600px max height to align with Chrome, that seems to do this automatically

I suppose it's a decent compromise, but I'm not sure I like that. if you have a 4k display (or even 1440p), limiting the height to 600 and forcing a scrollbar isn't ideal.

**Comment by AlecRust** [comment] 2022-03-20 17:50
Personally I wouldn't want it much taller than 600px before I get a scrollbar, but I'm not bothered by what pixel value is chosen. Or are you suggesting the height should not be limited at all?

Question is, does the latest build fix the "Can't scroll all the way down" issue?

Either way AFAIK the original reported issue here seems resolved with no regressions.

**Comment by Nojuuu** [comment] 2022-03-20 17:51
> Regarding "when it gets smaller" I'm not sure how much of an issue this is.  

It happens only if window is at bottom of the screen because it seems to force it to reduce height when it is placed there. This issue seems to still be there but other one was fixed.

**Comment by AronHK** [comment] 2022-03-20 18:24
>Personally I wouldn't want it much taller than 600px before I get a scrollbar, but I'm not bothered by what pixel value is chosen.

if you want the fix to work on smaller resolutions you can't go much higher. it's already too tall if you do 150% scaling on a 1080p monitor:
![image](https://user-images.githubusercontent.com/9072794/159176231-3798a2c3-ec40-45a7-be3a-a55b84029b29.png)
(of course this isn't a common setting.)

>Or are you suggesting the height should not be limited at all?

that would be my preference, or something close to it. I have a higher resolution monitor to see more things at once than on a 1080p one.
I tried making it something like 80% of the window height the last time I was messing around with it, but I wasn't able to do it.

I'm not against fixing it this way, I would just prefer it if there was another solution...

**Comment by AlecRust** [comment] 2022-03-20 18:47
> It happens only if window is at bottom of the screen because it seems to force it to reduce height when it is placed there.

I don't have an immediate fix for this. Considering it's a bit of an edge case, I think it should be a separate issue.

> if you want the fix to work on smaller resolutions you can't go much higher. it's already too tall if you do 150% scaling on a 1080p monitor

Can't we just use [resolution](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution) media queries to just set a different max height based on screen resolution?

Anyway #1237 seems to close this issue (horizontal scrollbars/misalignment).

The "can't scroll to the bottom in some cases" and "no max height of popup" issues look to be related/the same issue.

I can remove the current `max-height` fix from #1237 if you have concerns, and we look at that as a separate issue?

Personally, I would be inclined to release the `max-height` fix, as based on comments here it fixes the "can't scroll to the bottom in some cases" issue i.e. the latest build on that PR seems to have the least issues in Firefox thus far.

**Comment by Nojuuu** [comment] 2022-03-20 19:00
I think the max height fix should be fine for now.

**Comment by AronHK** [comment] 2022-03-20 19:06
>Personally, I would be inclined to release the max-height fix

sure. it may be improved upon later.

**Closed** 2022-04-22 19:26 UTC
