### ISSUE TITLE
Feature: Compatibility with youtube music (website version)

### ISSUE THREAD

**Issue by PedroAlfNeto** [ajayyy/SponsorBlock#1634] opened 2023-01-05 15:08 UTC
Google has been pressing video versions of music available in **music.**youtube.com (trying to force users to buy premium).
SponsorBlock to the rescue!! 

The interface to add new sections (category: Music:Non-music section) used in the website **music.**youtube.com is a bit buggy, since the way the video elements are managed are different. I can't click the buttons in "Submit Segment" settings.
So, for now, I switch to the video in **youtube.com** and after adding the segment, its available as well in **music.**youtube.com .

Suporting the **music.**youtube.com would probably lead to users adding more section, most of  the songs don't yet have sections to skip non music parts.

**Comment by PedroAlfNeto** [comment] 2023-01-05 15:09
maybe even removing other section options on **music.**youtube.com, or other ways to simplify reporting what isn't "music" would be awesome too

**Comment by mchangrh** [comment] 2023-01-05 19:32
duplicate of #1628 
related to #1532

**Closed** 2023-01-05 19:49 UTC
