### ISSUE TITLE
[Bug] Skipping segments returns the video playback to the beginning

### ISSUE THREAD

**Issue by T-Dimov** [ajayyy/SponsorBlock#1240] opened 2022-03-20 00:03 UTC
It has happened to me several times but I'm not entirely sure what the reproduction criteria are. Maybe it happens on the first play through of the video and at locations where marked segments overlap or are close to each other. On this video (I'm not sure if the timestamp matters) https://www.youtube.com/watch?v=SMUAZ1stSLk&t=333s it happened 2 times at 20:47 and at 28:39. Can YouTube chapters be at play as well? Sorry I'm being so vague, I don't have enough data to narrow it down. Of the segments in this video I have "Endcards/Credits" set to "Manual Skip" and all the rest are "Auto Skip".

Edit 22.03.:
This video restarted at the end as well: https://www.youtube.com/watch?v=0YDy6ygIjfY
Again there are overlapping segments. And I was voting on segments when it happened (don't know if relevant).

This one restarded, too: https://youtu.be/zDujFhvgUzI
There aren't even any overlapping segments...

**Comment by ajayyy** [comment] 2022-03-20 02:09
Browser, extension version?

**Comment by T-Dimov** [comment] 2022-03-20 09:13
Firefox 98.0.1 64 bit
SponsorBlock v. 4.2.1

**Comment by mchangrh** [comment] 2022-03-22 02:19
is it possible that the player container picked up your "skip" keypress as selecting "repeat" ?

**Comment by T-Dimov** [comment] 2022-03-22 18:13
Haven't pressed anything in these cases so I doubt it.

**Comment by pederbe** [comment] 2022-05-02 07:17
I have the same issue and it has been this way for at least half a year. But it only happens to one particular channel that I frequently watch (see below). I don't click any buttons or do anything unusual (I think) before this issue occurs. 

Here's a recent example for me: https://www.youtube.com/watch?v=_HRZR4vnpoA

Steps to reproduce:
1. Set SponsorBlock to automatically skip all types of segments.
2. Watch this video ( https://youtu.be/_HRZR4vnpoA ) from the beginning. 
3. When the video gets to the 15:45 mark it will automatically skip back to the beginning.

System

- Firefox 99.0.1 (64-bit)
- SponsorBlock v. 4.2.1

Other extensions:

- uBlock Origin
- Video Speed Controller
- Dark Reader

**Comment by mchangrh** [comment] 2022-05-02 17:08
That video does seem to have a segment that ends before the video is over, I'm not discounting a user not ending their segments properly across that entire channel

**Comment by pederbe** [comment] 2022-05-29 18:31
This issue is still occurring on at least some videos, such as the one linked below. Would it please be possible to investigate the issue or do you need any more information before that can happen? Cheers.

https://www.youtube.com/watch?v=sVWxw5W8cMs

**Comment by mchangrh** [comment] 2022-05-29 19:00
Is this happening consistently on these videos? 15/22 minutes to try to reproduce a bug is ***extremely*** time intensive and very hard to investigate if it's not consistent

**Comment by pederbe** [comment] 2022-06-15 12:30
> Is this happening consistently on these videos? 15/22 minutes to try to reproduce a bug is _**extremely**_ time intensive and very hard to investigate if it's not consistent

I tracked down a specific segment that has this issue. Hopefully that will allow you to see in the database if there are any obvious issues. Here it is:

SegmentID: 6c1affd9bd3cfce1e7e4440dc0c09868d44a60ad0cbdb8c653a972a553be5c6c6

**Comment by mchangrh** [comment] 2022-06-16 21:08
I can't reproduce it with just that segment. Can you recreate it like with https://github.com/ajayyy/SponsorBlock/issues/1027 ? that video also had a replaying issue and it was much shorter (20s)

**Comment by mayfrogs** [comment] 2022-12-03 23:45
I have this issue as well. For me it consistently happens on **all videos** that have TWO sponsorship segments where one of the sponsorship segments is a short mention at the very beginning of the video. The placement of the second sponsorship segment varies, but the first sponsorship segment is always at the very beginning of the video, starting at 0:00. Youtube user [iilluminaughtii](https://www.youtube.com/@iilluminaughtii) does this quite frequently, so it happens with a significant portion of her videos. An example of a video that I experienced this issue with is here: https://www.youtube.com/watch?v=-ckwOSqxhwo

**Comment by mchangrh** [comment] 2022-12-04 00:20
@mayfrogs can you post your debug and the version of the sponsorblock extension you are using?

**Comment by mayfrogs** [comment] 2022-12-04 00:32
Using Sponsorblock v. 5.1.8.
Debug:
`{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0",
        "platform": "Win32",
        "language": "en-US",
        "extensionVersion": "5.1.8"
    },
    "config": {
        "skipCount": 393,
        "autoSkipOnMusicVideosUpdate": true,
        "invidiousInstances": 11,
        "categoryPillUpdate": true,
        "isVip": false,
        "unsubmittedSegments": {
            "aDtnSrGq9dM": [],
            "XlznhdGuvWg": []
        },
        "minutesSaved": 473.80249866666696,
        "showPopupDonationCount": 5,
        "payments": {
            "licenseKey": null,
            "lastCheck": 0,
            "lastFreeCheck": 1670113715572,
            "freeAccess": false,
            "chaptersAllowed": false
        },
        "permissions": {
            "sponsor": true,
            "selfpromo": true,
            "exclusive_access": true,
            "interaction": true,
            "intro": true,
            "outro": true,
            "preview": true,
            "music_offtopic": true,
            "filler": true,
            "poi_highlight": true,
            "chapter": false
        },
        "defaultCategory": "chooseACategory",
        "renderSegmentsAsChapters": false,
        "whitelistedChannels": 0,
        "forceChannelCheck": false,
        "sponsorTimesContributed": 0,
        "submissionCountSinceCategories": 0,
        "showTimeWithSkips": true,
        "disableSkipping": false,
        "muteSegments": true,
        "fullVideoSegments": true,
        "manualSkipOnFullVideo": false,
        "trackViewCount": true,
        "trackViewCountInPrivate": true,
        "trackDownvotes": true,
        "dontShowNotice": false,
        "noticeVisibilityMode": 3,
        "hideVideoPlayerControls": false,
        "hideInfoButtonPlayerControls": false,
        "hideDeleteButtonPlayerControls": false,
        "hideUploadButtonPlayerControls": false,
        "hideSkipButtonPlayerControls": false,
        "hideDiscordLaunches": 0,
        "hideDiscordLink": false,
        "supportInvidious": false,
        "serverAddress": "Default server address",
        "minDuration": 0,
        "skipNoticeDuration": 4,
        "audioNotificationOnSkip": false,
        "checkForUnlistedVideos": false,
        "testingServer": false,
        "refetchWhenNotFound": true,
        "ytInfoPermissionGranted": false,
        "allowExpirements": true,
        "showDonationLink": true,
        "showUpsells": true,
        "donateClicked": 0,
        "autoHideInfoButton": true,
        "autoSkipOnMusicVideos": false,
        "scrollToEditTimeUpdate": false,
        "showChapterInfoMessage": true,
        "darkMode": true,
        "showCategoryGuidelines": true,
        "showCategoryWithoutPermission": false,
        "showSegmentNameInChapterBar": true,
        "useVirtualTime": true,
        "showSegmentFailedToFetchWarning": true,
        "categoryPillColors": {},
        "skipKeybind": {
            "key": "Enter"
        },
        "startSponsorKeybind": {
            "key": ";"
        },
        "submitKeybind": {
            "key": "'"
        },
        "nextChapterKeybind": {
            "key": "]",
            "ctrl": true
        },
        "previousChapterKeybind": {
            "key": "[",
            "ctrl": true
        },
        "categorySelections": [
            {
                "name": "sponsor",
                "option": 2
            },
            {
                "name": "poi_highlight",
                "option": 1
            },
            {
                "name": "exclusive_access",
                "option": 0
            }
        ],
        "colorPalette": {
            "red": "#780303",
            "white": "#ffffff",
            "locked": "#ffc83d"
        },
        "barTypes": {
            "preview-chooseACategory": {
                "color": "#ffffff",
                "opacity": "0.7"
            },
            "sponsor": {
                "color": "#00d400",
                "opacity": "0.7"
            },
            "preview-sponsor": {
                "color": "#007800",
                "opacity": "0.7"
            },
            "selfpromo": {
                "color": "#ffff00",
                "opacity": "0.7"
            },
            "preview-selfpromo": {
                "color": "#bfbf35",
                "opacity": "0.7"
            },
            "exclusive_access": {
                "color": "#008a5c",
                "opacity": "0.7"
            },
            "interaction": {
                "color": "#cc00ff",
                "opacity": "0.7"
            },
            "preview-interaction": {
                "color": "#6c0087",
                "opacity": "0.7"
            },
            "intro": {
                "color": "#00ffff",
                "opacity": "0.7"
            },
            "preview-intro": {
                "color": "#008080",
                "opacity": "0.7"
            },
            "outro": {
                "color": "#0202ed",
                "opacity": "0.7"
            },
            "preview-outro": {
                "color": "#000070",
                "opacity": "0.7"
            },
            "preview": {
                "color": "#008fd6",
                "opacity": "0.7"
            },
            "preview-preview": {
                "color": "#005799",
                "opacity": "0.7"
            },
            "music_offtopic": {
                "color": "#ff9900",
                "opacity": "0.7"
            },
            "preview-music_offtopic": {
                "color": "#a6634a",
                "opacity": "0.7"
            },
            "poi_highlight": {
                "color": "#ff1684",
                "opacity": "0.7"
            },
            "preview-poi_highlight": {
                "color": "#9b044c",
                "opacity": "0.7"
            },
            "filler": {
                "color": "#7300FF",
                "opacity": "0.9"
            },
            "preview-filler": {
                "color": "#2E0066",
                "opacity": "0.7"
            }
        }
    }
}`

**Comment by T-Dimov** [comment] 2022-12-04 21:55
I have a sneaking suspicion in may happen in some cases when you skip to part of the video that's not yet loaded. But it's not consistent...

**Comment by ajayyy** [comment] 2023-10-18 23:57
I believe this will be fixed by https://github.com/ajayyy/SponsorBlock/commit/c8c141f5c9f0082863d9c3304c0cad17fe394b84

**Closed by ajayyy** 2023-10-18 23:57 UTC
